build:
  image: node:5.2.0
  commands:
    - npm install nvm -g
    - apt-get update && apt-get install lftp
    - npm install --production
    - npm start
cache:
  mount:
    - node_modules
    - .git
deploy:
  commands:
    - echo deploy
