build:
  image: node:5.2.0
  commands:
    - echo hello world 23456768
    - node -e "console.log('asdf');"
    - node -v
    - apt-get update && apt-get install lftp
  cache:
    mount:
      - node_modules
      - .git
