build:
  image: node:5.2.0
  commands:
    - npm install nvm -g
    - apt-get update && apt-get install lftp
    - npm install --production
    - npm start
  cache:
    mount:
      - node_modules
      - .git
deploy:
  piscis/drone-bash:
    commands:
      - -H 127.0.0.1 -- uname -s
      - -H 127.0.0.1 -- node -v
