build:
  image: node:5.2.0
  commands:
    - npm install nvm -g
    - apt-get update && apt-get install lftp
    - npm install --production
    - npm start
  cache:
    mount:
      - node_modules
      - .git
deploy:
  piscis/drone-bash:
    commands:
      - apt-get update
      - apt-get install nodejs npm -y
      - npm install nvm -g
      - nvm install 5.2.2
      - nvm use 5.2.2
      - npm start
